#!/usr/bin/env bash
# Fetch Supabase API keys via CLI, save locally, and sync Railway env vars.
#
# Prerequisites:
#   brew install supabase/tap/supabase
#   supabase login   # or: supabase login --token "$SUPABASE_ACCESS_TOKEN"
#
# Usage:
#   ./scripts/sync-supabase-secrets.sh
#   ./scripts/sync-supabase-secrets.sh --railway   # also push publishable key to Railway
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "${ROOT_DIR}"

PROJECT_REF="${SUPABASE_PROJECT_REF:-qyxrbcbmatbaywyjrtug}"
OUT_FILE="${SUPABASE_SECRETS_FILE:-${ROOT_DIR}/.env.supabase.local}"
SYNC_RAILWAY=0

for arg in "$@"; do
  case "${arg}" in
    --railway) SYNC_RAILWAY=1 ;;
    -h|--help)
      sed -n '2,12p' "$0"
      exit 0
      ;;
    *)
      echo "Unknown argument: ${arg}" >&2
      exit 1
      ;;
  esac
done

if ! command -v supabase >/dev/null 2>&1; then
  echo "Supabase CLI not found. Install: brew install supabase/tap/supabase" >&2
  exit 1
fi

if ! supabase projects list >/dev/null 2>&1; then
  echo "Not logged in. Run: supabase login" >&2
  echo "Or: supabase login --token \"\$SUPABASE_ACCESS_TOKEN\"" >&2
  echo "Create a token at https://supabase.com/dashboard/account/tokens" >&2
  exit 1
fi

echo "==> Fetching API keys for project ${PROJECT_REF}"
keys_json="$(supabase projects api-keys --project-ref "${PROJECT_REF}" -o json)"

eval "$(python3 - <<'PY' "${keys_json}" "${PROJECT_REF}" "${OUT_FILE}"
import json
import sys

raw = sys.argv[1]
project_ref = sys.argv[2]
out_file = sys.argv[3]
payload = json.loads(raw)

# CLI returns a list or {"api_keys": [...]} depending on version.
rows = payload if isinstance(payload, list) else payload.get("api_keys", payload)

publishable = ""
secret_meta = ""
for row in rows:
    if not isinstance(row, dict):
        continue
    key_type = str(row.get("type") or "").casefold()
    key_name = str(row.get("name") or "").casefold()
    value = str(row.get("api_key") or row.get("key") or row.get("value") or "")
    if not value:
        continue
    if key_type == "publishable" or value.startswith("sb_publishable_"):
        publishable = value
    elif key_type == "secret" or value.startswith("sb_secret_"):
        # CLI masks full secret values; keep name/prefix for rotation tracking.
        prefix = str(row.get("prefix") or value[:20])
        candidate = f"{key_name or 'secret'}:{prefix}"
        if not secret_meta or key_name == "mljobswarm":
            secret_meta = candidate

if not publishable:
    raise SystemExit("Could not find publishable key in Supabase CLI output")

url = f"https://{project_ref}.supabase.co"
lines = [
    "# Generated by scripts/sync-supabase-secrets.sh — never commit",
    f"SUPABASE_URL={url}",
    f"SUPABASE_ANON_KEY={publishable}",
]
if secret_meta:
    lines.append(f"# SUPABASE_SECRET_KEY is masked by CLI; copy full value from dashboard if needed")
    lines.append(f"SUPABASE_SECRET_KEY_REF={secret_meta}")

from pathlib import Path
Path(out_file).write_text("\n".join(lines) + "\n", encoding="utf-8")

print(f'export SUPABASE_URL="{url}"')
print(f'export SUPABASE_ANON_KEY="{publishable}"')
if secret_meta:
    print(f'export SUPABASE_SECRET_KEY_REF="{secret_meta}"')
print(f'export SUPABASE_SECRETS_FILE="{out_file}"')
PY
)"

echo "==> Wrote ${OUT_FILE}"
chmod 600 "${OUT_FILE}" 2>/dev/null || true

if [[ "${SYNC_RAILWAY}" -eq 1 ]]; then
  if ! command -v railway >/dev/null 2>&1; then
    echo "Railway CLI not found; skipped Railway sync." >&2
    exit 0
  fi
  echo "==> Syncing publishable key to Railway (SUPABASE_URL + SUPABASE_ANON_KEY)"
  railway variable set \
    "SUPABASE_URL=${SUPABASE_URL}" \
    "SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}" \
    --json >/dev/null
  echo "Railway variables updated."
fi

echo
echo "Done."
echo "  Local secrets file: ${OUT_FILE}"
echo "  Secret key stays local — the hosted app does not use it."
if [[ "${SYNC_RAILWAY}" -eq 0 ]]; then
  echo "  To push publishable key to Railway: ./scripts/sync-supabase-secrets.sh --railway"
fi